libman/libapp/urls.py
from django.conf.urls import url
from .views import create_books, add_book, get_books, BookView, \
    BookFormView

urlpatterns = [
    url(r'add_books/', create_books, name='create_books'),
    url(r'books_form/', add_book, name='add_book'),
    url(r'all_books/', get_books, name='get_books'),
    url(r'list_books/', BookView.as_view(), name="list_books"),
    url(r'form_views/', BookFormView.as_view(), name='book_form')
]

libman/libman/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'book', include('libapp.urls')),
    path(r'rest_book/', include('libapp.rest_urls'))
]

libman/libapp/models.py
from django.db import models
# Create your models here.
BOOK_CATEGORY = (('Electronics', 'ECE'),
                 ('Computers', 'CSE'),
                 ('Civil', 'CIVIL'),
                 ('Human Resources', 'HR'),
                 ('Finance', 'FIN'),
                 ('Marketing', 'MKT')
                )

AVAILABLE = (('Yes', 'Y'),
             ('No', 'N')
             )


class Book(models.Model):

    name = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    edition = models.IntegerField()
    category = models.CharField(max_length=20, choices=BOOK_CATEGORY)
    publisher = models.CharField(max_length=50)
    reviews = models.FloatField()
    available = models.CharField(max_length=5, choices=AVAILABLE)
    issued_date = models.DateTimeField(auto_now=True)
    return_date = models.DateTimeField()

    def __str__(self):
        return '{} -  {}'.format(self.name, self.edition)

libman/libapp/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = '__all__'

libman/libapp/views.py
# built-in imports
import os
from datetime import datetime

#third-party imports
import xlrd
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from django.views.decorators.cache import cache_page

#project-specific imports
from .models import Book
from .forms import BookForm


def create_books(request):

    books_file = r'C:\\Users\\User\\workspace\\libmanrepo\\libman\\Book1.xlsx'
    if os.path.exists(books_file):
        xl_workbook = xlrd.open_workbook(books_file)
        sheet_names = xl_workbook.sheet_names()
        xl_sheet = xl_workbook.sheet_by_name(sheet_names[0])

        for row_idx in range(1, xl_sheet.nrows):
            data = xl_sheet.row_values(row_idx)
            year, month, day, hour, minute, second = xlrd.xldate_as_tuple(data[7], xl_workbook.datemode)
            issued_date = datetime(year, month, day).strftime('%Y-%m-%d')
            y, m, d, h, mn, s = xlrd.xldate_as_tuple(data[8], xl_workbook.datemode)
            return_date = datetime(y, m, d).strftime('%Y-%m-%d')
            #import pdb;pdb.set_trace()
            b, created = Book.objects.get_or_create(name=data[0], author=data[1], edition=data[2],
                                           category=data[3], publisher=data[4], reviews=data[5],
                                           available=data[6], issued_date=issued_date, return_date=return_date)
        return HttpResponse("Book details were added Successfully.")
    else:
        raise AttributeError("File path doesn't exist")


def add_book(request):

    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            raise form.ValidationErrors('Enter valid data.')

        return HttpResponseRedirect('/book/all_books/')

    else:
        form = BookForm()

    return render(request, 'book_form.html', {'book_form': form})


@cache_page(3*60)
def get_books(request):
    data = Book.objects.all().order_by('-edition', 'reviews')
    return render(request, 'get_books.html', {'book_data': data})


class BookView(ListView):

    model = Book
    queryset = Book.objects.all()
    template_name = 'get_books.html'
    #context_object_name = 'books_data'


class BookFormView(FormView):

    form_class = BookForm
    success_url = '/book/list_books'
    template_name = 'book_form.html'

    def form_valid(self, form):
        form.save()
        return redirect(self.success_url)

libman/templates/book_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Form</title>
</head>
<body align="center">

    <h1> Create Form</h1>
    <form  method=POST>
        {% csrf_token %} {{form.as_p}}
        <button type="submit">Submit</button>
    </form>

</body>
</html>

libman/templates/get_books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All Books</title>
</head>
<body>
    <h1 align="center"> Welcome to Library Management </h1>

    <table border="2px solid black" align="center">

        <th>ID</th>
        <th>Name</th>
        <th>Author</th>
        <th>Edition</th>
        <th>Category</th>
        <th>Publisher</th>
        <th>Reviews</th>
        <th>Available</th>
        <th>Issued Date</th>
        <th>Return Date</th>

        {% for val in  book_list%}
            <tr>
                <td>{{val.id}}</td>
                <td>{{val.name}}</td>
                <td>{{val.author}}</td>
                <td>{{val.edition}}</td>
                <td>{{val.category}}</td>
                <td>{{val.publisher}}</td>
                <td>{{val.reviews}}</td>
                <td>{{val.available}}</td>
                <td>{{val.issued_date}}</td>
                <td>{{val.return_date}}</td>
            </tr>
        {% endfor %}

    </table>

</body>
</html>